import "../styles/globals.css";
import { Toaster } from "react-hot-toast";
import Head from "next/head";



function MyApp({ Component, pageProps }) {
  return (
    <>
     <Head>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <Toaster
  position="top-left"
  reverseOrder={false}
  gutter={30}
  containerClassName=""
  containerStyle={{top: 150,}}
  toastOptions={{
    // Define default options
    className: '',
    duration: 2000,
    style: {
      background: 'orange',
      color: 'blue',
    },
    // Default options for specific types
    success: {
      duration: 3000,
      theme: {
        primary: 'green',
        secondary: 'black',
      },
    },
  }}
/>

    </>
  );
}

export default MyApp;
