import Head from "next/head";
import styles from "../styles/Home.module.css";
import toast from "react-hot-toast";
import { Footer } from "../components/Footer";
import { Links } from "../components/Links";
import { Headline } from "../components/Headline";

export default function Home() {

  const handleClick = ()=>toast('今は3番です');

  return (
    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline  page="index"/>

        <button onClick={handleClick} className={styles.card}>
          <h2>react_next.js学習進捗状況</h2>
          <p>ファイル名&rarr;react_toast</p>
        </button>

        <Links />
      </main>

      <Footer />
    </div>
  );
}
